Repository BinaryStudioAcademy/bsa-2021-mindbridge, pull requests merged in 2021-09, with the labels that each got.

#151 Feature/comment card
  backend/core/app/src/main/java/com/mindbridge/core/domains/comment/CommentController.java
  backend/core/app/src/main/java/com/mindbridge/core/domains/comment/CommentMapper.java
  backend/core/app/src/main/java/com/mindbridge/core/domains/comment/CommentService.java
  backend/core/app/src/main/java/com/mindbridge/core/domains/comment/dto/CreateCommentDto.java
  backend/core/app/src/main/java/com/mindbridge/core/domains/comment/dto/ReplyCommentDto.java
  backend/core/app/src/main/java/com/mindbridge/core/domains/commentReaction/CommentReactionController.java
  backend/core/app/src/main/java/com/mindbridge/core/domains/commentReaction/CommentReactionMapper.java
  backend/core/app/src/main/java/com/mindbridge/core/domains/commentReaction/CommentReactionService.java
  backend/core/app/src/main/java/com/mindbridge/core/domains/commentReaction/dto/ReceivedCommentReactionDto.java
  backend/core/app/src/main/java/com/mindbridge/core/domains/commentReaction/dto/ResponseCommentReactionDto.java
  backend/core/app/src/main/java/com/mindbridge/core/domains/commentReaction/dto/UserReactionsCommentsDto.java
  backend/core/app/src/main/java/com/mindbridge/core/domains/user/UserController.java
  backend/core/app/src/main/java/com/mindbridge/core/domains/user/UserService.java
  backend/core/app/src/main/java/com/mindbridge/core/domains/user/dto/UserProfileDto.java
  backend/core/db/src/main/java/com/mindbridge/data/domains/comment/CommentRepository.java
  backend/core/db/src/main/java/com/mindbridge/data/domains/comment/model/Comment.java
  backend/core/db/src/main/java/com/mindbridge/data/domains/commentReaction/CommentReactionRepository.java
  backend/core/db/src/main/java/com/mindbridge/data/domains/user/UserRepository.java
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/AdvancedCommentCard/AdvancedComment/index.tsx
  frontend/src/components/AdvancedCommentCard/AdvancedComment/styles.module.scss
  frontend/src/components/AdvancedCommentCard/Reply/index.tsx
  frontend/src/components/AdvancedCommentCard/Reply/styles.module.scss
  frontend/src/components/AdvancedCommentCard/index.tsx
  frontend/src/components/AdvancedCommentCard/mentition/mentition.tsx
  frontend/src/components/AdvancedCommentCard/mentition/provideValue.tsx
  frontend/src/components/AdvancedCommentCard/mentition/styles.module.scss
  frontend/src/components/AdvancedCommentCard/styles.module.scss
  frontend/src/components/AdvancedCommentCard/svg/ArrowCloseComment.tsx
  frontend/src/components/AdvancedCommentCard/svg/LinkSvg.tsx
  frontend/src/components/AdvancedCommentCard/svg/shareCommentSvg.tsx
  frontend/src/components/BasicCommentCard/components/BasicComment/index.tsx
  frontend/src/components/BasicCommentCard/components/Reply/styles.module.scss
  frontend/src/components/BasicCommentCard/index.tsx
  frontend/src/screens/PostPage/containers/reducer.ts
  frontend/src/screens/PostPage/models/IUserProfile.ts
  frontend/src/screens/PostPage/models/IUserReactionComments.ts
  frontend/src/screens/PostPage/reducers/index.ts
  frontend/src/screens/PostPage/routines/index.ts
  frontend/src/screens/ViewPost/components/ViewPostCard/index.tsx
  frontend/src/screens/ViewPost/containers/ViewPostPage/index.tsx
  frontend/src/screens/ViewPost/containers/ViewPostPage/reducer.ts
  frontend/src/screens/ViewPost/containers/ViewPostPage/sagas.ts
  frontend/src/screens/ViewPost/models/IComment.ts
  frontend/src/screens/ViewPost/models/ICommentReply.ts
  frontend/src/screens/ViewPost/models/IPost.ts
  frontend/src/screens/ViewPost/reducers/index.ts
  frontend/src/screens/ViewPost/routines/index.ts
  frontend/src/screens/ViewPost/services/viewPage.ts
Labels: enhancement

#156 ignore images in seeDiff
  frontend/src/components/TextRenderWithDiff/index.tsx
Labels: bug

#162 Patch/fix view post page visual issues
  frontend/src/components/TagComponent/styles.module.scss
  frontend/src/screens/ViewPost/components/Button/FollowBtn/styles.module.scss
  frontend/src/screens/ViewPost/components/ViewPostCard/styles.module.scss
Labels: bug

#168 Patch/fix private routes
  frontend/src/containers/Routing/index.tsx
  frontend/src/screens/FeedPage/containers/FeedPage/index.tsx
  frontend/src/screens/ProfilePage/containers/PublicProfilePage/index.tsx
  frontend/src/screens/ViewPost/containers/ViewPostPage/index.tsx
Labels: bug

#167 Feature/kindle saving quotes
  backend/core/app/src/main/java/com/mindbridge/core/domains/highlight/HighlightController.java
  backend/core/app/src/main/java/com/mindbridge/core/domains/highlight/HighlightMapper.java
  backend/core/app/src/main/java/com/mindbridge/core/domains/highlight/HighlightService.java
  backend/core/app/src/main/java/com/mindbridge/core/domains/highlight/dto/HighlightsDetailsDto.java
  backend/core/app/src/main/java/com/mindbridge/core/domains/highlight/dto/SavaHighlightDto.java
  backend/core/app/src/main/resources/db/common/V9_add_range_params_to_highlights.sql
  backend/core/db/src/main/java/com/mindbridge/data/domains/highlight/HighlightRepository.java
  backend/core/db/src/main/java/com/mindbridge/data/domains/highlight/model/Highlight.java
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/FeedTagsSideBar/index.tsx
  frontend/src/components/ProfileSidebar/index.tsx
  frontend/src/containers/Routing/index.tsx
  frontend/src/reducers.ts
  frontend/src/sagas.ts
  frontend/src/screens/HighlightsPage/components/highlightCard.tsx
  frontend/src/screens/HighlightsPage/components/styles.module.scss
  frontend/src/screens/HighlightsPage/containers/HighlightsPage/index.tsx
  frontend/src/screens/HighlightsPage/containers/HighlightsPage/reducer.ts
  frontend/src/screens/HighlightsPage/containers/HighlightsPage/sagas.ts
  frontend/src/screens/HighlightsPage/containers/HighlightsPage/styles.module.scss
  frontend/src/screens/HighlightsPage/models/IHighlight.tsx
  frontend/src/screens/HighlightsPage/reducers/index.ts
  frontend/src/screens/HighlightsPage/routines/index.ts
  frontend/src/screens/HighlightsPage/sagas/index.ts
  frontend/src/screens/HighlightsPage/services/index.tsx
  frontend/src/screens/ViewPost/components/Popups/HighlightPopup.tsx
  frontend/src/screens/ViewPost/components/ViewPostCard/index.tsx
  frontend/src/screens/ViewPost/components/ViewPostCard/styles.module.scss
  frontend/src/screens/ViewPost/containers/ViewPostPage/index.tsx
  frontend/src/screens/ViewPost/containers/ViewPostPage/reducer.ts
  frontend/src/screens/ViewPost/containers/ViewPostPage/sagas.ts
  frontend/src/screens/ViewPost/helpers/cursorPosition.ts
  frontend/src/screens/ViewPost/helpers/validateSelection.ts
  frontend/src/screens/ViewPost/reducers/index.ts
  frontend/src/screens/ViewPost/routines/index.ts
  frontend/src/screens/ViewPost/services/viewPage.ts
Labels: enhancement

#169 change returned value of post request
  backend/core/app/src/main/java/com/mindbridge/core/domains/post/dto/PostDetailsDto.java
  backend/core/app/src/main/java/com/mindbridge/core/domains/user/UserMapper.java
  backend/core/app/src/main/java/com/mindbridge/core/domains/user/dto/PostAuthorDto.java
  test/specs/api/mindbridge.postman_collection.json
Labels: bug

#179 Feature/favourites page
  backend/core/app/src/main/java/com/mindbridge/core/domains/favourite/FavouriteController.java
  backend/core/app/src/main/java/com/mindbridge/core/domains/favourite/FavouriteMapper.java
  backend/core/app/src/main/java/com/mindbridge/core/domains/favourite/FavouriteService.java
  backend/core/app/src/main/java/com/mindbridge/core/domains/favourite/dto/CreateFavouriteDto.java
  backend/core/app/src/main/java/com/mindbridge/core/domains/favourite/dto/FavouritePostsIdDto.java
  backend/core/app/src/main/java/com/mindbridge/core/domains/post/PostController.java
  backend/core/app/src/main/java/com/mindbridge/core/domains/post/PostMapper.java
  backend/core/app/src/main/java/com/mindbridge/core/domains/post/PostService.java
  backend/core/app/src/main/java/com/mindbridge/core/domains/post/dto/PostDetailsDto.java
  backend/core/app/src/main/java/com/mindbridge/core/domains/post/dto/PostsListDetailsDto.java
  backend/core/db/src/main/java/com/mindbridge/data/domains/favorite/FavoriteRepository.java
  frontend/src/components/AdvancedCommentCard/AdvancedComment/index.tsx
  frontend/src/components/FeedSvgComponents/favouriteSvg.tsx
  frontend/src/components/FeedSvgComponents/styles.module.scss
  frontend/src/components/PostCard/index.tsx
  frontend/src/components/ProfileSidebar/index.tsx
  frontend/src/components/RatingIcon/index.tsx
  frontend/src/components/TextRenderWithDiff/index.tsx
  frontend/src/containers/Routing/index.tsx
  frontend/src/reducers.ts
  frontend/src/sagas.ts
  frontend/src/screens/FavouritesPage/containers/FavouritesPagePage/index.tsx
  frontend/src/screens/FavouritesPage/containers/FavouritesPagePage/reducer.ts
  frontend/src/screens/FavouritesPage/containers/FavouritesPagePage/sagas.ts
  frontend/src/screens/FavouritesPage/containers/FavouritesPagePage/styles.module.scss
  frontend/src/screens/FavouritesPage/reducers/index.ts
  frontend/src/screens/FavouritesPage/routines/index.ts
  frontend/src/screens/FavouritesPage/sagas/index.ts
  frontend/src/screens/FavouritesPage/service/index.tsx
  frontend/src/screens/FeedPage/containers/FeedPage/index.tsx
  frontend/src/screens/FeedPage/containers/FeedPage/reducer.ts
  frontend/src/screens/FeedPage/models/IPostFeed.ts
  frontend/src/screens/FeedPage/models/IPostList.ts
  frontend/src/screens/Login/reducers/index.ts
  frontend/src/screens/PostPage/containers/EditPostPage/index.tsx
  frontend/src/screens/PostPage/containers/EditPrPage/index.tsx
  frontend/src/screens/PostPage/containers/reducer.ts
  frontend/src/screens/PostVersions/containers/PostVersionsPage/index.tsx
  frontend/src/screens/ProfilePage/containers/PublicProfilePage/index.tsx
  frontend/src/screens/PullRequest/containers/PullRequestPage/reducer.ts
  frontend/src/screens/Sidebar/containers/SidebarPage/index.tsx
  frontend/src/screens/ViewPost/components/ViewPostCard/index.tsx
  frontend/src/screens/ViewPost/components/svgs/SvgComponents/favouriteSvg.tsx
  frontend/src/screens/ViewPost/containers/ViewPostPage/index.tsx
  frontend/src/screens/ViewPost/containers/ViewPostPage/reducer.ts
  frontend/src/screens/ViewPost/models/IPost.ts
Labels: enhancement

#180 add rating and followers
  frontend/src/screens/Sidebar/containers/SidebarPage/index.tsx
Labels: bug

#181 Remove 'share' from the comments
  frontend/src/components/AdvancedCommentCard/AdvancedComment/index.tsx
  frontend/src/screens/Drafts/containers/DraftsPage/styles.module.scss
Labels: enhancement

#185 Feature/visible rating for author
  frontend/src/components/AdvancedCommentCard/AdvancedComment/index.tsx
  frontend/src/components/AdvancedCommentCard/Reply/index.tsx
  frontend/src/components/AdvancedCommentCard/index.tsx
  frontend/src/screens/ViewPost/components/ViewPostCard/index.tsx
  frontend/src/screens/ViewPost/components/svgs/RatingIcon/index.tsx
  frontend/src/screens/ViewPost/containers/ViewPostPage/index.tsx
Labels: enhancement

#188 Add title to 'Pull request page'
  frontend/src/screens/PostPage/containers/EditPostPage/index.tsx
  frontend/src/screens/PostPage/containers/styles.module.scss
Labels: enhancement

#184 add post share
  frontend/src/components/PostCard/index.tsx
  frontend/src/screens/ViewPost/components/Popups/SharePopup.tsx
  frontend/src/screens/ViewPost/components/ViewPostCard/index.tsx
Labels: enhancement

#186 Determine if post/comment was liked or disliked at backend
  backend/core/app/src/main/java/com/mindbridge/core/domains/post/PostController.java
  backend/core/app/src/main/java/com/mindbridge/core/domains/post/PostService.java
  backend/core/app/src/main/java/com/mindbridge/core/domains/post/dto/PostDetailsDto.java
  backend/core/app/src/main/java/com/mindbridge/core/domains/post/dto/PostsListDetailsDto.java
  backend/core/app/src/main/java/com/mindbridge/core/domains/postPR/PostPRController.java
  backend/core/app/src/main/java/com/mindbridge/core/domains/postPR/PostPRService.java
  backend/core/app/src/main/java/com/mindbridge/core/domains/postReaction/PostReactionService.java
  backend/core/app/src/main/java/com/mindbridge/core/domains/postReaction/dto/ResponsePostReactionDto.java
  frontend/src/components/PostCard/index.tsx
  frontend/src/screens/FeedPage/containers/FeedPage/index.tsx
  frontend/src/screens/FeedPage/containers/FeedPage/reducer.ts
  frontend/src/screens/FeedPage/containers/FeedPage/styles.module.scss
  frontend/src/screens/FeedPage/models/IPostFeed.ts
  frontend/src/screens/PostPage/containers/reducer.ts
  frontend/src/screens/PostPage/reducers/index.ts
  frontend/src/screens/PostPage/routines/index.ts
  frontend/src/screens/ViewPost/components/ViewPostCard/index.tsx
  frontend/src/screens/ViewPost/containers/ViewPostPage/index.tsx
  frontend/src/screens/ViewPost/containers/ViewPostPage/reducer.ts
  frontend/src/screens/ViewPost/models/IPost.ts
  test/specs/api/mindbridge.postman_collection.json
Labels: bug

#183 Change items of profile sidebar
  backend/core/app/src/main/java/com/mindbridge/core/domains/post/PostController.java
  backend/core/app/src/main/java/com/mindbridge/core/domains/post/PostService.java
  backend/core/app/src/main/java/com/mindbridge/core/domains/post/dto/DraftsListDto.java
  backend/core/db/src/main/java/com/mindbridge/data/domains/post/PostRepository.java
  frontend/src/components/ProfileSidebar/index.tsx
  frontend/src/containers/Routing/index.tsx
  frontend/src/screens/Drafts/components/DraftListItem/DraftListItem.tsx
  frontend/src/screens/Drafts/containers/DraftsPage/index.tsx
  frontend/src/screens/Drafts/containers/DraftsPage/sagas.ts
  frontend/src/screens/Drafts/containers/DraftsPage/styles.module.scss
  frontend/src/screens/Drafts/models/IDraft.ts
  frontend/src/screens/Drafts/reducers/index.ts
  frontend/src/screens/Drafts/services/Drafts.ts
Labels: enhancement

#212 Patch/fix image style
  frontend/src/screens/ViewPost/components/RelatedPosts/index.tsx
  frontend/src/screens/ViewPost/components/RelatedPosts/styles.module.scss
Labels: bug

#210 Feature/grey like buttons for author
  frontend/src/screens/ViewPost/components/svgs/RatingIcon/index.tsx
Labels: enhancement

#192 Feature/followers modal window
  backend/core/app/src/main/java/com/mindbridge/core/domains/user/UserService.java
  backend/core/app/src/main/java/com/mindbridge/core/domains/user/dto/FollowerDto.java
  backend/core/app/src/main/java/com/mindbridge/core/domains/user/dto/FollowingDto.java
  backend/core/app/src/main/java/com/mindbridge/core/domains/user/dto/UserProfileDto.java
  backend/core/db/src/main/java/com/mindbridge/data/domains/follower/FollowerRepository.java
  frontend/src/screens/ProfilePage/components/FollowerCard/index.tsx
  frontend/src/screens/ProfilePage/components/FollowerCard/styles.module.scss
  frontend/src/screens/ProfilePage/components/FollowersModal/index.tsx
  frontend/src/screens/ProfilePage/components/FollowersModal/styles.module.scss
  frontend/src/screens/ProfilePage/components/PublicProfileCard/index.tsx
  frontend/src/screens/ProfilePage/components/PublicProfileCard/styles.module.scss
  frontend/src/screens/ProfilePage/components/svg/followersSvg.jsx
  frontend/src/screens/ProfilePage/containers/reducer.ts
  frontend/src/screens/ProfilePage/models/IFollower.ts
  frontend/src/screens/ProfilePage/models/IUser.ts
Labels: enhancement

#217 Patch/fix edit comment style
  frontend/src/components/AdvancedCommentCard/AdvancedComment/index.tsx
  frontend/src/components/AdvancedCommentCard/mentition/commentInputStyle.module.scss
Labels: hotfix

#218 Patch/search by enter
  frontend/src/screens/FeedPage/containers/FeedPage/index.tsx
  frontend/src/screens/Header/containers/HeaderPage/index.tsx
Labels: hotfix

#221 Feature/change favourite icon
  frontend/src/components/FeedSvgComponents/favouriteSvg.tsx
  frontend/src/components/PostCard/index.tsx
  frontend/src/screens/ViewPost/components/ViewPostCard/index.tsx
Labels: enhancement

#233 Patch/fix search dropdown
  frontend/src/components/FoundPostsList/styles.module.scss
  frontend/src/screens/Header/containers/HeaderPage/index.tsx
  frontend/src/screens/Header/containers/HeaderPage/styles.module.scss
Labels: bug

#232 Feature/add placeholders on load data
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/AdvancedCommentCard/AdvancedComment/index.tsx
  frontend/src/components/PostCard/index.tsx
  frontend/src/components/PostCard/styles.module.scss
  frontend/src/components/PostHistorySidebar/index.tsx
  frontend/src/components/PostHistorySidebar/styles.module.scss
  frontend/src/components/ProfileSidebar/index.tsx
  frontend/src/components/ProfileSidebar/styles.module.scss
  frontend/src/components/TagComponent/index.tsx
  frontend/src/screens/FavouritesPage/containers/FavouritesPagePage/index.tsx
  frontend/src/screens/FavouritesPage/containers/FavouritesPagePage/reducer.ts
  frontend/src/screens/FeedPage/containers/FeedPage/index.tsx
  frontend/src/screens/PostPage/reducers/index.ts
  frontend/src/screens/Sidebar/containers/SidebarPage/index.tsx
  frontend/src/screens/ViewPost/components/ViewPostCard/index.tsx
  frontend/src/screens/ViewPost/components/ViewPostCard/styles.module.scss
  frontend/src/screens/ViewPost/components/svgs/RatingIcon/index.tsx
  frontend/src/screens/ViewPost/containers/ViewPostPage/index.tsx
Labels: enhancement

#234 Patch/fix comment block on draft page
  frontend/src/components/CreatePostForm/styles.module.scss
  frontend/src/components/FeedTagsSideBar/styles.module.scss
  frontend/src/components/buttons/Blue_button/styles.module.scss
  frontend/src/components/buttons/ColorlessButton/styles.module.scss
  frontend/src/components/buttons/DarcBorderButton/styles.module.scss
  frontend/src/components/buttons/DarcButton/styles.module.scss
  frontend/src/screens/Header/containers/HeaderPage/styles.module.scss
  frontend/src/screens/Header/containers/HeaderPage/svg/bellSvg.jsx
  frontend/src/screens/PostPage/containers/styles.module.scss
  frontend/src/screens/ViewPost/components/ViewPostCard/index.tsx
Labels: bug

#237 left icons on the draft page are not active
  frontend/src/screens/ViewPost/components/ViewPostCard/index.tsx
  frontend/src/screens/ViewPost/components/ViewPostCard/styles.module.scss
Labels: merge conflicts
